networks:
 app_network:
    name: ${COMPOSE_PROJECT_NAME}
    driver: bridge

services:

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
      args:
        - NGINX_VERSION=${NGINX_VERSION}
        - APP_DOMAIN=${APP_DOMAIN}
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    depends_on:
      - php
      - mysql
      - redis
      - meilisearch
      - phpmyadmin
      - kafka
    ports:
      - ${HTTP_ON_HOST}:80
      - ${HTTPS_ON_HOST}:443
    volumes:
      - ${PATH_TO_CODE}:/var/www/html
    networks:
      - app_network

  php:
    #user: 1000:1000
    #platform: linux/amd64
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_php_${PHP_VERSION}
    volumes:
      - ${PATH_TO_CODE}:/var/www/html
      - ./supervisor/:/var/log/nats/
    networks:
      - app_network

  mysql:
    #image: mariadb:${MARIADB_VERSION}
    image: arm64v8/mysql:${MYSQL_VERSION}
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    ports:
      - ${MYSQL_ON_HOST}:3306
    volumes:
      - ./database/data/${COMPOSE_PROJECT_NAME}_data:/var/lib/mysql
    networks:
      - app_network
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  composer:
    #user: 1000:1000
    #platform: linux/amd64
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_composer_${PHP_VERSION}
    volumes:
      - ${PATH_TO_CODE}:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "/bin/composer.phar"]
    networks:
      - app_network

  artisan:
    #user: 1000:1000
    #platform: linux/amd64
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_artisan_${PHP_VERSION}
    volumes:
      - ${PATH_TO_CODE}:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan"]
    networks:
      - app_network

  npm:
    image: node:${NODE_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_npm
    volumes:
      - ${PATH_TO_CODE}:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - app_network

  phpunit:
    #user: 1000:1000
    #platform: linux/amd64
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_phpunit_${PHP_VERSION}
    volumes:
      - ${PATH_TO_CODE}:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["/var/www/html/vendor/bin/phpunit"]
    networks:
      - app_network

  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    ports:
      - ${REDIS_ON_HOST}:6379
    networks:
      - app_network

  horizon:
    #user: 1000:1000
    #platform: linux/amd64
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_horizon_${PHP_VERSION}
    volumes:
      - ${PATH_TO_CODE}:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan", "horizon"]
    networks:
      - app_network

  cron:
    #user: 1000:1000
    #platform: linux/amd64
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_cron_${PHP_VERSION}
    volumes:
      - ${PATH_TO_CODE}:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["crond", "-f"]
    networks:
      - app_network

  phpmyadmin:
    #user: 1000:1000
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    env_file:
      - .env
    environment:
      PMA_HOST: ${PMA_HOST} # Change this to your MySQL container name
      UPLOAD_LIMIT: ${PHP_MY_ADMIN_UPLOAD_LIMIT}

    networks:
      - app_network

  meilisearch:
    # Uncomment and adjust user if needed
    # user: 1000:1000
    # Uncomment and adjust platform if needed
    # platform: linux/amd64
    image: getmeili/meilisearch:latest
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME}_meilisearch
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS}
      - MEILI_ENV=${MEILI_ENV}
      - MEILI_LOG_LEVEL=${MEILI_LOG_LEVEL}
    env_file:
      - .env
    volumes:
      - ./meilisearch/data/${COMPOSE_PROJECT_NAME}_data:/meili_data
    networks:
      - app_network
    ports:
      - ${MEILISEARCH_ON_HOST}:7700

  rabbitmq:
    image: rabbitmq:management
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME}_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    ports:
      - ${RABBITMQ_AMQP_PORT}:5672  # AMQP protocol
      - ${RABBITMQ_MANAGEMENT_PORT}:15672  # Management UI
    networks:
      - app_network

  zookeeper:
    image: bitnami/zookeeper:latest
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME}_zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app_network

  kafka:
    image: bitnami/kafka:latest
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME}_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"  # Local client connections
      - "9093:9093"  # Controller communication
      - "9094:9094"  # External remote access
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@${COMPOSE_PROJECT_NAME}_kafka:9093"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,PLAINTEXT_EXTERNAL://:9094,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_EXTERNAL://192.168.0.116:9094"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "${COMPOSE_PROJECT_NAME}_zookeeper:2181"
    networks:
      - app_network